### ISSUE TITLE
Memory Leak on all pages in Chrome

### ISSUE THREAD

**Issue by jah6842** [Overv/Open.GL#29]
Left the site open while doing other stuff for a few hours, came back to this:

![image](https://cloud.githubusercontent.com/assets/6118869/3821394/0bf4c328-1d0c-11e4-9045-e0276fa0f5a1.png)

Win7, Google Chrome Version 36.0.1985.125 m, run in Incognito Mode (disables extensions)

To Reproduce: 
1. Open any Open.gl page in Chrome
2. Watch memory usage slowly climb

Usage only grows when the page is in view. Minimizing will stop the growth.

Have not tested in other browsers.

**Comment by blackwolf12333** [comment]
No problem here, Arch Linux, Chromium 39.0.2171.99-1

**Comment by jah6842** [comment]
Appears to be resolved, as of Chrome Version 39.0.2171.99 m
