### ISSUE TITLE
Epub version

### ISSUE THREAD

**Issue by fenuks** [Overv/Open.GL#34]
Are there any chances for epub version. Since this book is written in markdown, creating ebook with [gitbook](https://www.gitbook.com) should be easy.

**Comment by Overv** [comment]
I'll consider it, but I'll have to investigate how well gitbook works with the math expressions and such.

**Comment by emersont1** [comment]
you'll need to change the images though to ```![](url)```

**Comment by serialhex** [comment]
I second the epub, and if possible pdf would be nice also!  I imagine that using gitbook as previously stated would give you pdf generation for free essentially.

**Comment by Overv** [comment]
I just tried to use gitbook to make a PDF, but I had a very bad experience. The editor I used to convert the site to the gitbook version of Markdown kept freezing and used 1 GB of RAM, and I when I tried to use npm to install the PDF exporter, I got some unknown JavaScript error. I think someone with gitbook experience should convert it and then I'll link it here.

**Comment by emersont1** [comment]
Maybe try Pandoc, I think it supports pretty much every format under the sun

**Comment by maluramichael** [comment]
This would be so cool. Was searching exactly for this.

**Comment by Overv** [comment]
I could try Pandoc, since magicbook doesn't support epub.

**Comment by Overv** [comment]
Pandoc is great, there are now EPUB and PDF versions of the guide available, see the README for links!

**Comment by maluramichael** [comment]
Really nice. Only the epub version has some errors. 
![mosaic capture 2017-05-3 at 08 43 57](https://cloud.githubusercontent.com/assets/1489383/25650368/acaae172-2fdc-11e7-9be2-af09a5679669.png)

**Comment by Overv** [comment]
@maluramichael Can you check if this one works for you?

https://drive.google.com/file/d/0Bznk3iw2H5blZjdrR0NSOWwxQUk/view?usp=sharing

**Comment by maluramichael** [comment]
@Overv yea this looks much better
![image](https://cloud.githubusercontent.com/assets/1489383/25675606/6272bfb8-303f-11e7-9b25-b87a37984c2a.png)
