### ISSUE TITLE
GLM uses radians since 0.9.6.0

### ISSUE THREAD

**Issue by Mischa-Alff** [Overv/Open.GL#35]
Since version `0.9.6.0`, GLM broke compatibility with previous versions to use radians instead of degrees.

 I'd gladly make a PR to fix this in the code/articles, but I was wondering if it was more desirable to do e.g `glm::radians(45.0f)`, or simply `3.1415f/4.f`, or use `const float pi = std::acos(-1);`, and do `pi/4.f`?

I personally think `glm::radians(45.0f)` is more understandable/readable to someone who is new to graphics programming and/or inexperienced in trigonometry.

**Comment by Overv** [comment]
Yes, `glm::radians` would make the most sense.
