### ISSUE TITLE
how do you license your code?

### ISSUE THREAD

**Issue by sudoman** [Overv/Open.GL#38]
hello, and great site! thanks for taking the time to put it up.

i'm planning on basing some of my floss code on what you have here. would you mind specifying which license you'd like to offer your code with? i probably shouldn't entwine our code without knowing that's a-ok with you.

if you'd like to use a permissive license, i suggest [apache 2.0](https://gnu.org/licenses/license-list.html#apache2) or [CC0](https://gnu.org/licenses/license-list.html#CC0). thanks!

**Comment by Overv** [comment]
I've added license info to the README.

**Comment by sudoman** [comment]
thanks!
