### ISSUE TITLE
Quickstart Boilerplate

### ISSUE THREAD

**Issue by Polytonic** [Overv/Open.GL#43]
I put together an [OpenGL quickstart boilerplate](https://github.com/Polytonic/Glitter) a while back while working through your tutorials and the [LearnOpenGL](http://learnopengl.com/) tutorials. I opened an issue to add it to LearnOpenGL see [LearnOpenGL#11](https://github.com/JoeyDeVries/LearnOpenGL/issues/11). I figured this may be of interest to this series of tutorials as well. Basically it bundles all the dependencies as submodules and statically compiles/links to avoid any dll-copying or installation headaches. I've verified that it works across all major platforms.

Is this of any use to you?

**Comment by Overv** [comment]
Nice work! I've added a link in the sidebar and a reference to it in the context creation chapter.

**Comment by Polytonic** [comment]
Awesome!  One more comment:

>You'll just have to install SOIL separately.

I actually bundle [stb](https://github.com/nothings/stb) which includes [stb_image](https://github.com/nothings/stb/blob/master/stb_image.h). SOIL wraps stb_image, and it looked unmaintained when I last checked it out. I don't know how much of the extra bits of SOIL you are using (e.g. cubemaps). It may be possible to just get by with stb, and then not have to link with SOIL's libfile.

**SOIL**
```c++
unsigned char* image = SOIL_load_image("img.png", &width, &height, 0, SOIL_LOAD_RGB);
```

**STB** (see [Glitter/Samples/mesh.cpp#L139](https://github.com/Polytonic/Glitter/blob/master/Samples/mesh.cpp#L139) for a full example)
```c++
unsigned char* image = stbi_load("img.png", &width, &height, &channels, 0);
```

**Comment by Overv** [comment]
Fair enough, I'll see if I can change the main tutorial to use STB.
