### ISSUE TITLE
Ad obscures text when at small screen width

### ISSUE THREAD

**Issue by alexdmiller** [Overv/Open.GL#48]
If the browser screen is under a certain width, the ad snaps over to the right hand side and obscures the text. It makes the tutorial very frustrating to use when you have a small browser window.

**Comment by Overv** [comment]
You're right, it currently makes it unusable on mobile devices. I'll see what I can do to improve that.

**Comment by Overv** [comment]
The check for Android has been replaced by a proper responsive ad layout.
