### ISSUE TITLE
glDrawElements clarification

### ISSUE THREAD

**Issue by AngeloG** [Overv/Open.GL#52]
So I just ran into an issue similar to this: https://stackoverflow.com/questions/23026612/gldrawelements-crash-opengl-3-2-windows-7

Perhaps it's worth noting that if you bind `GL_ELEMENT_ARRAY_BUFFER` before binding a VAO, it will use the (null) element buffer currently bound to an (empty) VAO. Just my 2 cents.

**Comment by Overv** [comment]
I admit that the placement of the section is a bit unfortunate, but the VAO section already mentions:

>Since only calls after binding a VAO stick to it, make sure that you've created and bound the VAO at the start of your program.

I've changed it to be highlighted as a warning and added an extra sentence:

>Since only calls after binding a VAO stick to it, make sure that you've created and bound the VAO at the start of your program. Any vertex buffers and element buffers bound before it will be ignored.

See https://open.gl/drawing

**Comment by AngeloG** [comment]
Looks good! :+1:
