### ISSUE TITLE
Matrix stuff doesn't work after glm v0.9.9.0 removed default initialization

### ISSUE THREAD

**Issue by mortie** [Overv/Open.GL#66]
On page 55 of the current version of the PDF (at https://raw.githubusercontent.com/Overv/Open.GL/master/ebook/Modern%20OpenGL%20Guide.pdf), the book includes these lines:

```
glm::mat4 trans;
trans = glm::rotate(trans, glm::radians(180.0f), glm::vec3(0.0f, 0.0f, 1.0f));
```

That doesn't work anymore, since glm v0.9.9.0 removed default initialization of vectors and matrices. It should probably be replaced with something like this:

```
float identmat[] = {
	1, 0, 0, 0,
	0, 1, 0, 0,
	0, 0, 1, 0,
	0, 0, 0, 1,
};
glm::mat4 trans = glm::make_mat4(identmat);
trans = glm::rotate(trans, glm::radians(180.0f), glm::vec3(0.0f, 0.0f, 1.0f));
```

**Comment by mgerhardy** [comment]
afair this is enough:
`glm::mat4 trans(0);`

**Comment by mortie** [comment]
That doesn't seem to work, at least on my version of GLM (v0.9.9.3). It seems to zero initialize the matrix, not initialize it to the identity matrix.

**Comment by mgerhardy** [comment]
ah sorry - not 0 of course - but:
`glm::mat4 trans(1.0f);`

**Comment by Overv** [comment]
I've updated the ebook versions.
