### ISSUE TITLE
Ambiguity in the description

### ISSUE THREAD

**Issue by JerzySpendel** [Overv/Open.GL#71]
In the section of drawing (https://open.gl/drawing) in the section "Combining shaders into a program
" you talk about drawing to buffers, but in this context I think you meant framebuffer, or I am mistaken? I'm a newbie in terms of OpenGL, but if you meant framebuffer you should have written "framebuffer" especially when earlier you talk about buffers as a structure for uploading data from the program, so it's becoming confusing.

**Comment by Overv** [comment]
That wording is indeed a bit confusing and I've changed it. Thanks for the suggestion.
